mac: ./assignment1/main.cpp
	clang++ -std=c++20 -lglut -rpath @executable_path/ -framework OpenGL ./assignment1/main.cpp -o main

windows: main.cpp
	echo "good luck bucko"

clean:
	rm -f *.out
	rm -f *.o
	rm -f main
